### ISSUE TITLE
Extension already used

### ISSUE THREAD

**Issue by alex-lairan** [JoshuaManton/crest#1]
Hello ! 

Thanks for this language and good luck. :muscle: 

Unfortunately, the extension `.cr` is already used by Crystal lang, so you are indexed on https://crystalshards.xyz/ website.

**Comment by JoshuaManton** [comment]
Sounds like a problem with crystalshards more than anything 😛 

In all seriousness this is a toy project and "crest" is a working title, so I'm not too concerned. Thank you for the warning though!
